.TH "TestLoadBalancer" 3 "Wed Oct 12 2022" "Version 0.0.1" "CS 412 Load Balancer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestLoadBalancer \- Class used to test components of the load balancer\&. Mainly used to simulate load balancing\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <test\-load\-balancer\&.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBtestRequestQueue\fP ()"
.br
.RI "Test the \fBRequestQueue\fP class and the different funcitonalities it has\&. "
.ti -1c
.RI "static void \fBtestServer\fP ()"
.br
.RI "Test the \fBServer\fP class and the different functionalities it has\&. "
.ti -1c
.RI "static void \fBtestServerGroup\fP ()"
.br
.RI "Test the \fBServerGroup\fP class and the different functionalities it has\&. "
.ti -1c
.RI "static void \fBsimulateLoadBalancer\fP (int initRequestAmount, int initServerAmount, int clockCycles)"
.br
.RI "Simulate load balancing with an initial amount of requests, initial server amount, and clock cycles this load balancer will be running for\&. "
.in -1c
.SH "Detailed Description"
.PP 
Class used to test components of the load balancer\&. Mainly used to simulate load balancing\&. 


.SH "Member Function Documentation"
.PP 
.SS "void TestLoadBalancer::simulateLoadBalancer (int initRequestAmount, int initServerAmount, int clockCycles)\fC [static]\fP"

.PP
Simulate load balancing with an initial amount of requests, initial server amount, and clock cycles this load balancer will be running for\&. As the simulation runs, there will be new requests added to the request queue every 10 to 150 clock cycles\&.
.PP
\fBParameters\fP
.RS 4
\fIinitRequestAmount\fP Initial amount of requests the request queue will start out with 
.br
\fIinitServerAmount\fP Initial amount of servers the server group will start out with 
.br
\fIclockCycles\fP The amount of clock cycles the simulation will run for 
.RE
.PP

.SS "void TestLoadBalancer::testRequestQueue ()\fC [static]\fP"

.PP
Test the \fBRequestQueue\fP class and the different funcitonalities it has\&. 
.SS "void TestLoadBalancer::testServer ()\fC [static]\fP"

.PP
Test the \fBServer\fP class and the different functionalities it has\&. 
.SS "void TestLoadBalancer::testServerGroup ()\fC [static]\fP"

.PP
Test the \fBServerGroup\fP class and the different functionalities it has\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for CS 412 Load Balancer from the source code\&.
